server:
  port: 8501

logging:
  level:
    org.springframework.cloud: DEBUG
    com.bluelion: DEBUG
spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.bluelion.usercenter.entity
