spring:
  redis:
    host: localhost
    port: 6379
    password: ~
    jedis:
      pool:
        max-wait: 3s
        min-idle: 50
        max-idle: 1000
        max-active: 2000
    timeout: 5s
  datasource:
    url: jdbc:mysql://localhost:3306/bluelion_user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123qwe
    driver-class-name: com.mysql.jdbc.Driver