consul:
  image: consul
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"

bluelion-usercenter:
  image: gaoshan/bluelion-usercenter
  ports:
    - "8501:8501"
  links:
    - "consul"

bluelion-order:
  image: gaoshan/bluelion-order
  ports:
  - "8504:8504"
  links:
  - "consul"
  - "bluelion-usercenter"

bluelion-content:
  image: gaoshan/bluelion-content
  ports:
  - "8505:8505"
  links:
  - "consul"
  - "bluelion-usercenter"

bluelion-gateway:
  image: gaoshan/bluelion-gateway
  ports:
  - "8502:8502"
  links:
  - "consul"
  - "bluelion-usercenter"
  - "bluelion-order"
  - "bluelion-content"