spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bluelion_auth?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123qwe
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0